CinemaTicket.Web/Models/Showtime.cs
using System.ComponentModel.DataAnnotations;

namespace CinemaTicket.Web.Models
{
    public class Showtime : BaseEntity
    {
        [Display(Name = "Ngày")]
        public DateOnly Date { get; set; }

        public int SccreeningRoomId { get; set; }

        [Display(Name = "Tên phòng")]
        public string ScreeningRoomName { get; set; } = string.Empty;

        [Display(Name = "Loại phòng")]
        public string ScreeningRoomType { get; set; } = string.Empty;

        public int ShowtimeScheduleId { get; set; }

        public string ShowtimeSchedule { get; set; } = string.Empty;

        public int MovieId { get; set; }

        [Display(Name = "Tên phim")]
        public string MovieTitle { get; set; } = string.Empty;

        [Display(Name = "Giá vé")]
        public double Price { get; set; }

        public int TheaterId { get; set; }

        [Display(Name = "Tên rạp")]
        public string TheaterName { get; set; } = string.Empty;

        public bool IsAvailable { get; set; }

        public ICollection<Seat>? Seats { get; set; }
    }
}

CinemaTicket.Web/Controllers/ShowtimesController.cs
using CinemaTicket.Core.Enums;
using CinemaTicket.Web.Dtos;
using CinemaTicket.Web.Models;
using CinemaTicket.Web.Services;
using CinemaTicket.Web.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace CinemaTicket.Web.Controllers
{
    public class ShowtimesController : Controller
    {
        private readonly ShowtimeService _showtimeService;
        private readonly MovieService _movieService;
        private readonly TheaterService _theaterService;
        private readonly UserService _userService;

        public ShowtimesController(ShowtimeService showtimeService, MovieService movieService,
            TheaterService theaterService, UserService userService)
        {
            _showtimeService = showtimeService;
            _movieService = movieService;
            _theaterService = theaterService;
            _userService = userService;
        }

        public async Task<IActionResult> Index([FromQuery] DateOnly? searchDate, [FromQuery] string? searchName, [FromQuery] int? scheduleType)
        {
            ViewBag.ScheduleTypes = GetScheduleTypes();

            var showtimes = await _showtimeService.GetAllAsync();

            GetScheduleTypes();

            if (!string.IsNullOrEmpty(searchName))
            {
                showtimes = showtimes!.Where(s => s.MovieTitle!.ToUpper().Contains(searchName.ToUpper()));
            }

            if (searchDate is not null)
            {
                showtimes = showtimes!.Where(x => x.Date == searchDate);
            }

            if (scheduleType is not null)
            {
                showtimes = showtimes!.Where(x => x.ShowtimeScheduleId == scheduleType);
            }

            return View(showtimes);
        }


        public async Task<IActionResult> ChooseTheater()
        {
            if (!_userService.IsLoggedIn)
            {
                return RedirectToAction("Index", "Account");
            }

            if (!IsAuthorized("OfficeManager") && !IsAuthorized("Administrator"))
            {
                var vm = new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = "Bạn không có quyền thực hiện yêu cầu này!"
                };

                return View("Error", vm);
            }

            var theaters = await _theaterService.GetAllAsync();

            ViewData["Theaters"] = new SelectList(theaters, "Id", "Name");
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Create([FromQuery] int theaterId)
        {
            var movieList = await _movieService.GetAllAsync();

            var theaters = await _theaterService.GetAllAsync();

            var theater = theaters!.Where(t => t.Id == theaterId).FirstOrDefault();

            if (theater is null)
            {
                return NotFound();
            }

            var rooms = theater.ScreeningRooms;

            var vm = new CreateShowtimeViewModel()
            {
                TheaterName = theater.Name,
                Movies = new SelectList(movieList, "Id", "Title"),
                ShowtimeSchedules = new SelectList(GetScheduleTypes(), "Value", "Text")
            };

            if (rooms!.Count == 0)
            {
                var items = new List<string> { "Chưa có phòng chiếu trong rạp này" };
                vm.ScreeningRooms = new SelectList(items);
            }
            else
            {
                vm.ScreeningRooms = new SelectList(rooms, "Id", "Name");
            }

            return View(vm);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CreateShowtimeDto CreateShowtimeDto)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var res = await _showtimeService.AddAsync(CreateShowtimeDto);

                    if (res is not null)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        return View("Error", new ErrorViewModel
                        {
                            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                            Message = "Có lỗi xảy ra khi thêm suất chiếu!"
                        });
                    }
                }
            }
            catch (DbUpdateException /* ex */)
            {
                //Log the error (uncomment ex variable name and write a log.
                ModelState.AddModelError("", "Unable to save changes. " +
                    "Try again, and if the problem persists " +
                    "see your system administrator.");
            }


            return View(CreateShowtimeDto);
        }

        private IEnumerable<ScheduleType> GetScheduleTypes()
        {
            var scheduleTypes = new List<ScheduleType>();

            foreach (var type in Enum.GetValues(typeof(ShowtimeScheduleEnum)))
            {
                scheduleTypes.Add(new ScheduleType
                {
                    Value = (int)type,
                    Text = type.ToString()!
                });
            }

            return scheduleTypes;
        }

        private bool IsAuthorized(string role)
        {
            return _userService.GetRoles().Contains(role);
        }

        [HttpGet]
        [Route("Showtimes/Details/{id}")]
        public async Task<IActionResult> Details(int id)
        {
            var showtime = await _showtimeService.GetShowtimeByIdAsync(id);
            if (showtime is null)
            {
                var vm = new ErrorViewModel
                {
                    RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier,
                    Message = "Không tìm thấy suất chiếu này!"
                };

                return View("Error", vm);
            }

            return View(showtime);
        }
    }
}

CinemaTicket.Web/Views/Showtimes/ChooseTheater.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Chọn rạp</h1>

<form asp-action="Create" asp-controller="Showtimes" method="get">
    <div class="form-group p-3">
        <select asp-items="ViewBag.Theaters" name="theaterId">
        </select>
    </div>

    <div class="form-group p-2">
        <input type="submit" class="btn btn-primary" value="Tiếp tục" />
    </div>
</form>

CinemaTicket.Web/Views/Showtimes/Create.cshtml
@using CinemaTicket.Web.ViewModels

@model CreateShowtimeViewModel

<h1>Tạo suất chiếu</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Showtimes" asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group p-2">
                <label class="control-label">Rạp</label>
                <input disabled class="form-control" type="text" value="@Model.TheaterName" />

            </div>

            <div class="form-group p-2">
                <label asp-for="CreateShowtimeDto.Date" class="control-label">Ngày</label>
                <input asp-for="CreateShowtimeDto.Date" class="form-control" type="date" />
                <span asp-validation-for="CreateShowtimeDto.Date" class="text-danger"></span>
            </div>

            <div class="form-group p-2">
                <label asp-for="CreateShowtimeDto.SccreeningRoomId" class="control-label">Phòng chiếu</label>

                <select asp-items="Model.ScreeningRooms" asp-for="CreateShowtimeDto.SccreeningRoomId" class="form-control"></select>

                <span asp-validation-for="CreateShowtimeDto.SccreeningRoomId" class="text-danger"></span>
            </div>

            <div class="form-group p-2">
                <label asp-for="CreateShowtimeDto.ShowtimeScheduleId" class="control-label">Khung giờ</label>

                @Html.DropDownListFor(m => m.CreateShowtimeDto.ShowtimeScheduleId, Model.ShowtimeSchedules, new { @class = "form-control" })

                <span asp-validation-for="CreateShowtimeDto.ShowtimeScheduleId" class="text-danger"></span>
            </div>

            <div class="form-group p-2">
                <label asp-for="CreateShowtimeDto.Price" class="control-label">Giá vé</label>
                <input asp-for="CreateShowtimeDto.Price" class="form-control" type="number" />
                <span asp-validation-for="CreateShowtimeDto.Price" class="text-danger"></span>
            </div>

            <div class="form-group p-2">
                <label asp-for="CreateShowtimeDto.MovieId" class="control-label">Phim</label>
                <select asp-for="CreateShowtimeDto.MovieId" asp-items="@Model.Movies" class="form-control">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CreateShowtimeDto.ShowtimeScheduleId" class="text-danger"></span>
            </div>

            <div class="form-group p-2">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="p-2">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CinemaTicket.Web/Views/Showtimes/Details.cshtml
@model Showtime



<div class="card border-info mb-3 w-75">
    <div class="row g-0">
        <div class="col-md-4">
            <img src="~/images/phim2.jpg" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
            <div class="card-body">
                <h5 class="card-title">@Model.MovieTitle</h5>
                <div>
                    <hr />
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Date)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Date)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.TheaterName)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.TheaterName)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.ScreeningRoomType)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ScreeningRoomType)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.ShowtimeSchedule)
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.ShowtimeSchedule)
                        </dd>
                        <dt>
                            @Html.DisplayNameFor(model => model.Price)
                        </dt>
                        <dd>
                            @String.Format("{0:0,0}", Model.Price)
                        </dd>
                    </dl>
                </div>

                <a asp-action="Index" asp-route-showtimeId="@Model.Id" asp-controller="Tickets" class="btn btn-info">
                    Bán vé
                </a>
            </div>
        </div>
    </div>
</div>

CinemaTicket.Web/Views/Showtimes/Index.cshtml
@model IEnumerable<Showtime>

@{
    ViewData["Title"] = "Lịch chiếu phim";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var data = ViewBag.ScheduleTypes;

    var selectList = new SelectList(data, "Value", "Text", 0);
}

<h1>@ViewData["Title"]</h1>

<p>
    <a class="btn btn-success" asp-action="ChooseTheater">Tạo mới</a>
</p>


@* <select asp-items="selectList"> *@
@*     <option value=""></option> *@
@* </select> *@

<form asp-controller="Showtimes" asp-action="Index" method="get">
    <p>
        <label>Tên phim: <input class="form-control" type="text" name="searchName" /></label>
        @* <input type="submit" value="Filter" /> *@

        <label class="m-1" for="searchSchedule">
            Ca chiếu:
            @* <input class="form-control" type="text" id="searchSchedule" name="searchSchedule"> *@


            @Html.DropDownList("scheduleType", new SelectList(ViewBag.ScheduleTypes, "Value", "Text"), new { @class = "form-control" })
        </label>

        <label class="m-1" for="searchDate">
            Ngày:
            <input class="form-control" type="date" id="searchDate" name="searchDate">
        </label>

        <button class="btn btn-primary" type="submit">Search</button>

    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ScreeningRoomName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ScreeningRoomType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShowtimeSchedule)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MovieTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TheaterName)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in @Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScreeningRoomName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ScreeningRoomType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ShowtimeSchedule)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MovieTitle)
                </td>
                <td class="text-end">
                    @* @Html.DisplayFor(modelItem => item.Price) *@
                    @String.Format("{0:#,##}", item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TheaterName)
                </td>
                <td>
                    <a class="btn-sm btn-info text-decoration-none" asp-controller="Tickets" asp-action="Index" asp-route-showtimeId="@item.Id">Bán vé</a>
                    <a class="btn-sm btn-warning text-decoration-none" asp-action="Details" asp-route-id="@item.Id">Chi tiết</a>
                </td>
            </tr>
        }
    </tbody>
</table>